In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
df =  pd.read_csv("world_alcohol.csv")
df.head(20)

,Year,WHO region,Country,Beverage Types,Display Value
0,1986,Western Pacific,Viet Nam,Wine,0.00
1,1986,Americas,Uruguay,Other,0.50
2,1985,Africa,Cte d'Ivoire,Wine,1.62
3,1986,Americas,Colombia,Beer,4.27
4,1987,Americas,Saint Kitts and Nevis,Beer,1.98
5,1987,Americas,Guatemala,Other,0.00
6,1987,Africa,Mauritius,Wine,0.13
7,1985,Africa,Angola,Spirits,0.39
8,1986,Americas,Antigua and Barbuda,Spirits,1.55
9,1984,Africa,Nigeria,Other,6.10
10,1987,Africa,Botswana,Wine,0.20
11,1989,Americas,Guatemala,Beer,0.62
12,1985,Western Pacific,Lao People's Democratic Republic,Beer,0.00
13,1984,Eastern Mediterranean,Afghanistan,Other,0.00
14,1985,Western Pacific,Viet Nam,Spirits,0.05
15,1987,Africa,Guinea-Bissau,Wine,0.07
16,1984,Americas,Costa Rica,Wine,0.06
17,1989,Africa,Seychelles,Beer,2.23
18,1984,Europe,Norway,Spirits,1.62
19,1984,Africa,Kenya,Beer,1.08

In [22]:
df[df['WHO region'].isin(["Africa", "Eastern Mediterranean", "Europe"])]

    Year WHO region            Country Beverage Types  Display Value
2   1985     Africa       Cte d'Ivoire           Wine           1.62
6   1987     Africa          Mauritius           Wine           0.13
7   1985     Africa             Angola        Spirits           0.39
9   1984     Africa            Nigeria          Other           6.10
10  1987     Africa           Botswana           Wine           0.20
..   ...        ...                ...            ...            ...
93  1987     Africa         Madagascar          Other            NaN
94  1985     Europe            Ukraine        Spirits           3.06
95  1984     Africa              Niger          Other           0.00
96  1985     Europe         Luxembourg           Wine           7.38
98  1984     Africa  Equatorial Guinea           Wine           0.00

[69 rows x 5 columns]